CREATE TABLE tx_packets (
	id INTEGER NOT NULL, 
	publisher_mesh_node_num VARCHAR, 
	publisher_discord_bot_user_id VARCHAR, 
	packet_id INTEGER, 
	channel INTEGER, 
	hop_limit INTEGER, 
	dest INTEGER, 
	dest_id VARCHAR, 
	dest_shortname VARCHAR, 
	dest_longname VARCHAR, 
	acknowledge_requested BOOLEAN, 
	acknowledge_received BOOLEAN, 
	discord_guild_id VARCHAR, 
	discord_channel_id VARCHAR, 
	discord_message_id VARCHAR, 
	discord_user_id VARCHAR, 
	discord_user_display_name VARCHAR, 
	discord_user_global_name VARCHAR, 
	discord_user_name VARCHAR, 
	discord_user_mention VARCHAR, 
	ts DATETIME, 
	PRIMARY KEY (id)
)

CREATE TABLE rx_packets (
	id INTEGER NOT NULL, 
	publisher_mesh_node_num VARCHAR, 
	publisher_discord_bot_user_id VARCHAR, 
	channel INTEGER, 
	src_num INTEGER, 
	src_id VARCHAR, 
	src_short_name VARCHAR, 
	src_long_name VARCHAR, 
	dst_num INTEGER, 
	dst_id VARCHAR, 
	dst_short_name VARCHAR, 
	dst_long_name VARCHAR, 
	hop_limit INTEGER, 
	hop_start INTEGER, 
	pki_encrypted BOOLEAN, 
	portnum VARCHAR, 
	priority VARCHAR, 
	rx_time INTEGER, 
	rx_rssi DOUBLE, 
	rx_snr DOUBLE, 
	to_all BOOLEAN, 
	want_ack BOOLEAN, 
	text VARCHAR, 
	bitfield INTEGER, 
	emoji INTEGER, 
	reply_id INTEGER, 
	telemetry_air_quality_metrics JSON, 
	telemetry_device_metrics JSON, 
	telemetry_environment_metrics JSON, 
	telemetry_power_metrics JSON, 
	has_air_quality_metrics BOOLEAN, 
	has_device_metrics BOOLEAN, 
	has_environment_metrics BOOLEAN, 
	has_power_metrics BOOLEAN, 
	has_position_data BOOLEAN, 
	altitude DOUBLE, 
	latitude DOUBLE, 
	"latitudeI" INTEGER, 
	longitude DOUBLE, 
	"longitudeI" INTEGER, 
	pos_time INTEGER, 
	location_source VARCHAR, 
	pdop DOUBLE, 
	ground_speed DOUBLE, 
	ground_track DOUBLE, 
	sats_in_view INTEGER, 
	precision_bits INTEGER, 
	node_id VARCHAR, 
	node_short_name VARCHAR, 
	node_long_name VARCHAR, 
	mac_address VARCHAR, 
	hw_model VARCHAR, 
	public_key VARCHAR, 
	request_id VARCHAR, 
	error_reason VARCHAR, 
	traceroute_data JSON, 
	ts DATETIME, pkt_id INTEGER, 
	PRIMARY KEY (id)
)

CREATE TABLE nodes (
	id INTEGER NOT NULL, 
	publisher_mesh_node_num VARCHAR, 
	publisher_discord_bot_user_id VARCHAR, 
	node_num INTEGER, 
	is_favorite BOOLEAN, 
	user_id_nodedb VARCHAR, 
	user_long_name_nodedb VARCHAR, 
	user_short_name_nodedb VARCHAR, 
	user_mac_addr_nodedb VARCHAR, 
	user_hw_model_nodedb VARCHAR, 
	user_public_key_nodedb VARCHAR, 
	user_id_nodeinfo VARCHAR, 
	user_long_name_nodeinfo VARCHAR, 
	user_short_name_nodeinfo VARCHAR, 
	user_mac_addr_nodeinfo VARCHAR, 
	user_hw_model_nodeinfo VARCHAR, 
	user_public_key_nodeinfo VARCHAR, 
	crt_ts DATETIME, 
	upd_ts_nodedb DATETIME, 
	upd_ts_nodeinfo DATETIME, 
	PRIMARY KEY (id)
)

CREATE TABLE acks (
	id INTEGER NOT NULL, 
	publisher_mesh_node_num VARCHAR, 
	publisher_discord_bot_user_id VARCHAR, 
	tx_packet_id INTEGER, 
	ack_packet_id INTEGER, 
	implicit_ack BOOLEAN, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tx_packet_id) REFERENCES tx_packets (id), 
	FOREIGN KEY(ack_packet_id) REFERENCES rx_packets (id)
)





