version: '3.8'

services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: postgres_db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      TZ: "${TZ}"
    volumes:
      - "postgres_data:${POSTGRES_VOLUME}"
    ports:
      - "5432:5432"
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}"
      - "GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}"
      - "TZ=${TZ}"
    volumes:
      - "grafana-storage:${GF_VOLUME}"
    depends_on:
      - postgres
  meshbot:
    image: "${MY_DOCKER_REG}/${MY_DOCKER_NAME}:${MY_DOCKER_VERSION}"
    container_name: meshtastic_discord_bot
    privileged: true
    environment:
      - "DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}"
      - "DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}"
      - "TIME_ZONE=${TZ}"
      - "CHANNEL_0=${CHANNEL_0}"
      - "CHANNEL_1=${CHANNEL_1}"
      - "INTERFACE_METHOD=${INTERFACE_METHOD}"
      - "INTERFACE_BLE_NODE=${INTERFACE_BLE_NODE}"
      - "DB_TYPE=${DB_TYPE}"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_NAME=${DB_NAME}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "TZ=${TZ}"
    volumes:
      - "meshbot-storage:/app/storage"
      - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"
    devices:
      - "/dev/bus/usb"
    restart: unless-stopped

volumes:
  postgres_data:
  grafana-storage:
  meshbot-storage: