version: '3.8'

services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: postgres_db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - "postgres_data:${POSTGRES_VOLUME}"
    ports:
      - "5432:5432"
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}"
      - "GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}"
    volumes:
      - "grafana-storage:${GF_VOLUME}"
    depends_on:
      - postgres

volumes:
  postgres_data:
  grafana-storage:
